name: main

on: 
    push:
        branches:
          - main
        paths:
          - .github/workflows/*
          - src/composite1/**            

    pull_request:    
        branches:
          - main
        types: 
          - opened
          - reopened
          - synchronize 
          #- closed

    workflow_dispatch:
        inputs:  
        
            publish:
                required: true
                type: boolean

            configuration:
                required: false
                type: choice
                options:
                - Debug
                - Release

            verbosity:
                required: false
                type: choice
                options:
                - quiet
                - minimal
                - normal
                - detailed
                - diagnostic

jobs:
  parameters:
    runs-on: ubuntu-latest
  
    outputs:      
      versionSuffix : ${{ steps.parameters.outputs.versionSuffix }}
      configuration : ${{ steps.parameters.outputs.configuration }}
      verbosity : ${{ steps.parameters.outputs.verbosity }}
      publish : ${{ steps.parameters.outputs.publish }}

    steps:
    - name: Setting up parameters
      id: parameters
      shell: pwsh
      run: |
        Write-Host "Setting up parameters"
        $suffixMap = @{"push"="alpha"; "pull_request"="beta"; "workflow_dispatch"=""};

        if('${{github.event_name}}' -eq 'workflow_dispatch'){
            echo "::set-output name=configuration::${{github.event.inputs.configuration}}"
            echo "::set-output name=verbosity::${{github.event.inputs.verbosity}}"
            echo "::set-output name=publish::${{github.event.inputs.publish}}"

        } else  {
            echo "::set-output name=configuration::Release"
            echo "::set-output name=verbosity::Minimal"
            echo "::set-output name=publish::true"
        }

        echo "::set-output name=versionSuffix::$($suffixMap['${{github.event_name}}'])"

    - name: printing printing parameters
      shell: pwsh
      run: |
        Write-Host "versionSuffix: $($env:versionSuffix)"
        Write-Host "publish: $($env:publish)"
        Write-Host "verbosity: $($env:verbosity)"
        Write-Host "configuration: $($env:configuration)"
      env:        
        versionSuffix : ${{ steps.parameters.outputs.versionSuffix }}        
        publish : ${{ steps.parameters.outputs.publish }}        
        verbosity : ${{ steps.parameters.outputs.verbosity }}        
        configuration : ${{ steps.parameters.outputs.configuration }}        

  main:
    needs: parameters
    uses: taori/actions/.github/workflows/nupkg.yml@main
    with:
      solutionPath: src/composite1/All.sln
      projectPath: src/composite1/composite1.csproj
      versionSuffix: ${{ needs.parameters.outputs.versionSuffix }}
      publish: ${{ needs.parameters.outputs.publish == true }}
      publishSnupkg: true
      packageId: demo.composite1
      removePrereleases: true
      configuration: ${{ needs.parameters.outputs.configuration }}
      verbosity: ${{ needs.parameters.outputs.verbosity }}
      dotnetVersion: 6.0.x
    secrets:
      nuget: ${{ secrets.NUGET }}
      