name: main

on: 
    push:
        branches:
          - main
        paths:
          - .github/workflows/*
          - src/composite1/**
        inputs:
            publish: true
            configuration: Release
            verbosity: minimal
            

    pull_request:    
        branches:
          - main
        types: 
          - opened
          - reopened
          - synchronize 
          #- closed
        inputs:
            publish: true
            configuration: Release
            verbosity: minimal

    workflow_dispatch:
        inputs:  
        
            publish:
                required: true
                type: boolean

            configuration:
                required: false
                type: choice
                options:
                - Debug
                - Release

            verbosity:
                required: false
                type: choice
                options:
                - quiet
                - minimal
                - normal
                - detailed
                - diagnostic

jobs:
  parameters:
    runs-on: ubuntu-latest
  
    outputs:      
      versionSuffix : ${{ steps.parameters.outputs.versionSuffix }}

    steps:
    - name: Setting up parameters
      id: parameters
      shell: pwsh
      run: |
        Write-Host "Setting up parameters"
        $suffixMap = @{"push"="alpha"; "pull_request"="beta"; "workflow_dispatch"=""};
        $suffix = $suffixMap['${{github.event_name}}']
        #$inputfallback = @{"push"="alpha"; "pull_request"="beta"; "workflow_dispatch"=""};
        Write-Host "event verbosity ${{github.event.inputs.verbosity}}"

        echo "::set-output name=versionSuffix::$($suffix)"

    - name: printing printing parameters
      shell: pwsh
      run: |
        Write-Host "versionSuffix: $($env:versionSuffix)"
      env:        
        versionSuffix : ${{ steps.parameters.outputs.versionSuffix }}        

  main:
    needs: parameters
    uses: taori/actions/.github/workflows/nupkg.yml@main
    with:
      solutionPath: src/composite1/All.sln
      projectPath: src/composite1/composite1.csproj
      versionSuffix: ${{ needs.parameters.outputs.versionSuffix }}
      publish: true        
      publishSnupkg: true
      packageId: demo.composite1
      removePrereleases: true
      configuration: Release
      verbosity: minimal
      dotnetVersion: 5.0.x, 6.0.x
    secrets:
      nuget: ${{ secrets.NUGET }}
      