name: Deploy to docker registry

on:
  workflow_call: 
    inputs: 
      registry:
        description: "Target registry. defaults to 'ghcr.io'"
        default: ghcr.io
        type: string
        
      imageName:
        description: "name of image. defaults to 'github.repository'"
        default: ${{ github.repository }}
        type: string
        
      imageTags:
        description: "version of the image. defaults to 'v1.0.0'"
        default: 'v1.0.0'
        type: string
        required: true
      
      dockerFilePath:
        description: "Path to the docker file. defaults to './Dockerfile'"
        default: "./Dockerfile"
        type: string
        
      dockerFileContext:
        description: "Path to the docker file. defaults to '.'"
        default: "."
        type: string
        
      push:
        description: "Whether the container should be pushed to the register. defaults to true"
        default: true
        type: boolean
        
      sign:
        description: "Whether to use signing. defaults to false"
        default: false
        type: boolean
        
      checkoutRef:
        description: "Git ref of deployment"
        required: false
        default: ${{ github.event.pull_request.head.ref }}
        type: string

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo in the console output
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience to skip caching NuGet packages and speed up the build
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry to Microsoft

jobs:
  deploy:
    name: Deploy to registry ${{inputs.registry}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Used for identity challenge with sigstore/fulcio

    steps:

      - name: Install Cosign
        if: ${{ inputs.sign }}
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b
        with:
          cosign-release: 'v1.9.0'
          
      - uses: actions/checkout@v4.1.7
        with:
          persist-credentials: true
          repository: ${{ github.event.pull_request.head.repo.full_name }} # required for commit
          ref: ${{ inputs.checkoutRef }} # required for commit

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325

      - name: Login to ${{ inputs.registry }} registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ${{ inputs.registry }}/${{ inputs.imageName }}

      - name: Build + Push Docker image
        id: build-and-push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: ${{ inputs.dockerFileContext }}
          file: ${{ inputs.dockerFilePath }}
          push: ${{ inputs.push }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ inputs.imageTags }}

      # Sign the Docker image digest
      # Uses the identity token to provision an ephemeral certificate against the community Fulcio instance
      # https://github.com/sigstore/cosign
      - name: Sign the Docker image
        if: ${{ inputs.sign }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}