name: Nuget

on:
  workflow_call:
    inputs:  
        
      solutionPath:
        required: true
        type: string
        
      projectPaths:
        required: true
        type: string
        
      versionSuffix:
        required: false
        type: string
        default: ""
        
      versionPrefix:
        required: false
        type: string
        default: ""
        
      packageIds:
        required: true
        type: string
        
      publish:
        required: true
        type: boolean
        
      package:
        required: true
        type: boolean
        
      publishSymbols:
        required: true
        type: boolean
        
      removePrereleases:
        required: false
        type: boolean
        default: false
        
      configuration:
        required: false
        type: string
        default: "Release"
        
      verbosity:
        required: false
        type: string
        default: "minimal"    
        
      dotnetVersion:
        required: false
        type: string
        default: "5.0.x, 6.0.x"
        
    secrets:
      nuget:
        required: true
  
jobs:
  
  build:
      
    concurrency:    
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    
    env:      
      versionSuffix : ${{ inputs.versionSuffix }}
      verbosity : ${{ inputs.verbosity }}
      configuration : ${{ inputs.configuration }}
      
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: nuget secret verification
      env:
        NUGET: ${{ secrets.nuget }}
      if: "${{ env.NUGET == '' }}"
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('"nuget" secret is missing')
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
             
    #- name: stop
    #  run: exit 1
      
    - uses: actions/checkout@v2 
      if: ${{ !inputs.skipSolutionBuild }}

    - name: Restore dependencies
      if: ${{ !inputs.skipSolutionBuild }}
      run: dotnet restore ${{ inputs.solutionPath }}
      
    - name: Build
      if: ${{ !inputs.skipSolutionBuild }}
      run: dotnet build ${{ inputs.solutionPath }} --verbosity $verbosity -c $configuration --no-restore 
      
    - name: Test
      if: ${{ !inputs.skipSolutionBuild }}
      run: dotnet test ${{ inputs.solutionPath }} --verbosity $verbosity -c $configuration --no-build 
              
    - name: Pack with csproj version
      shell: pwsh
      if: ${{ inputs.package && inputs.versionPrefix == '' }}
      run: |
        $projects = "${{ inputs.projectPaths }}".Split(";")
        foreach($project in $projects){
          dotnet pack $project --verbosity $verbosity -c $configuration -o artifacts/nupkg --no-build /p:VersionSuffix=$versionSuffix
        }        
              
    - name: Pack manual version
      shell: pwsh
      if: ${{ inputs.package && inputs.versionPrefix != '' }}
      run: |
        $projects = "${{ inputs.projectPaths }}".Split(";")
        foreach($project in $projects){
          dotnet pack $project --verbosity $verbosity -c $configuration -o artifacts/nupkg --no-build /p:VersionSuffix=$versionSuffix /p:VersionPrefix=${{ inputs.versionPrefix }}
        }   

    - name: Remove snupkg
      if: ${{ !inputs.publishSymbols && inputs.publish }}
      run: find artifacts/nupkg/ -name "*.snupkg" -type f -delete
      
    - name: Release
      if: ${{ inputs.publish }}
      run: dotnet nuget push "artifacts/nupkg/*.nupkg" -k ${{ secrets.nuget }} -s https://api.nuget.org/v3/index.json
      
    - name: Remove old prereleases 
      if: ${{ inputs.removePrereleases }}
      id: defaults
      shell: pwsh
      run: |  
        & dotnet tool install --global NugetUnlister
        $packages = Get-ChildItem "artifacts/nupkg/" -Filter "*.nupkg" |
         %{ $_.Name } |
         Select-String -Pattern "(?<packageId>[^\d]+)\.(?<version>[\w\d\.-]+)(?=.nupkg)" |
         %{ @($_.Matches[0].Groups["packageId"].Value, $_.Matches[0].Groups["version"].Value) } 
         
         foreach ($package in $packages){
          & nuget-unlist drop prereleasebefore $package[0] $package[1] ${{ secrets.nuget }}
         }
        
        $packageVersion = Get-ChildItem -Recurse -Filter '*.nupkg' | select { $_.Name } -ExpandProperty Name | Select-String -Pattern "\d[\d\w\.\+-]+(?=.nupkg)" | %{$_.Matches.Value}
        & nuget-unlist drop prereleasebefore ${{ inputs.packageId }} $packageVersion ${{ secrets.nuget }}
       
