name: Nuget

on:
  workflow_call:
    inputs:  
        
      solutionPath:
        required: true
        type: string
        
      projectPath:
        required: true
        type: string
        
      versionSuffix:
        required: false
        type: string
        default: ""
        
      publish:
        required: true
        type: boolean
        
      publishSymbols:
        required: true
        type: boolean
        
      packageId:
        required: true
        type: string
        
      removePrereleases:
        required: false
        type: boolean
        default: false
        
      configuration:
        required: false
        type: string
        default: "Release"
        
      verbosity:
        required: false
        type: string
        default: "minimal"    
        
      dotnetVersion:
        required: false
        type: string
        default: "5.0.x, 6.0.x"
        
    secrets:
      nuget:
        required: true
        
  workflow_dispatch:
  
jobs:
  
  build:
      
    concurrency:    
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    
    env:      
      versionSuffix : ${{ inputs.versionSuffix }}
      verbosity : ${{ inputs.verbosity }}
      configuration : ${{ inputs.configuration }}
      
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
             
    - name: JsonPublish
      if: ${{ fromJSON(inputs.publish) }}
      run: Write-Host "bla"
    - name: inputs.publish
      if: ${{inputs.publish}}
      run: Write-Host "bla"
    - name: true
      if: ${{inputs.publish == true}}
      run: Write-Host "bla"
    - name: escapedsingle
      if: ${{inputs.publish == 'true'}}
      run: Write-Host "bla"
    - name: escapedsingle2
      if: ${{ env:cond }}
      run: Write-Host "bla"
      with:
        cond : ${{ inputs.publish }}

    - name: stop
      run: exit 1
      
    - uses: actions/checkout@v2
    

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solutionPath }}
    - name: Build
      run: dotnet build ${{ inputs.solutionPath }} --verbosity $verbosity -c $configuration --no-restore 
    - name: Test
      run: dotnet test ${{ inputs.solutionPath }} --verbosity $verbosity -c $configuration --no-build 
              
    - name: Pack
      if: ${{ fromJSON(inputs.publish) }}
      run: dotnet pack ${{ inputs.projectPath }} --verbosity $verbosity -c $configuration -o artifacts/${{ inputs.packageId }} --no-build /p:VersionSuffix=$versionSuffix

    - name: Remove snupkg
      if: ${{ fromJSON(inputs.publishSymbols) && false }}
      run: find artifacts/${{ inputs.packageId }}/ -name "*.snupkg" -type f -delete
      
    - name: Release
      if: ${{ fromJSON(inputs.publish) && false }}
      run: dotnet nuget push "artifacts/${{ inputs.packageId }}/*.nupkg" -k ${{ secrets.nuget }} -s https://api.nuget.org/v3/index.json
      
    - name: Remove old prereleases 
      if: ${{ fromJSON(inputs.removePrereleases) && false }}
      id: defaults
      shell: pwsh
      run: |  
        & dotnet tool install --global NugetUnlister
        $packageVersion = Get-ChildItem -Recurse -Filter '*.nupkg' | select { $_.Name } -ExpandProperty Name -First 1 | Select-String -Pattern "\d[\d\w\.\+-]+(?=.nupkg)" | %{$_.Matches.Value}
        & nuget-unlist drop prereleasebefore ${{ inputs.packageId }} $packageVersion ${{ secrets.nuget }}
       
