name: update nupkg readme

on:
  workflow_call:
    
    inputs:
      readmePath:
        type: string
        required: true
        description: ''
        
      artifactName:
        description: 'name of the artifact that contains the nuget packages'
        type: string
        required: true
      
      debugWorkflow:
        required: false
        type: boolean
        default: false

jobs:
  
  update:
    
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

      - uses: actions/checkout@v4.1.7
        with:
          persist-credentials: true
          repository: ${{ github.event.pull_request.head.repo.full_name }} # required for commit
          ref: ${{ github.event.pull_request.head.ref }} # required for commit  
          
      - name: Download nupkg artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ./artifact-export
          
      - name: unzip packages
        shell: pwsh
        run: Get-ChildItem -Path ./artifact-export -Filter "*.nupkg" | ForEach-Object { Expand-Archive -Path $_.FullName -DestinationPath "./unzipped/$($_.Name)/" }

      - name: modify contents
        shell: pwsh
        run: |
          Copy-Item -Recurse -Path ./unzipped -Destination ./modified
          Get-ChildItem -Path ./modified -Filter "README.md" -Recurse | ForEach-Object { Copy-Item ./README.md -Destination $_.FullName -Force }
          New-Item ./zipped -Type Directory
          Get-ChildItem -Path ./modified -Filter "*.nupkg" -Recurse | ForEach-Object { Compress-Archive -Path $_.FullName -DestinationPath "./zipped/$($_.Name)" }

      - name: delete old artifact
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.deleteArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: ${{ inputs.artifactName }}
            });
            
      - name: upload modified artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ inputs.artifactName }}
          path: ./zipped/*.nupkg
          if-no-files-found: error
          retention-days: 1